jira:
  image: jira:7.2.8
  container_name: jira
  restart: always
  volumes:
   - "/opt/atlassian:/var/atlassian"
   - "/opt/jiralogs:/opt/atlassian/jira/logs"
  ports:
   - 8080:8080
  environment:
   - JVM_MINIMUM_MEMORY="1024m"
   - JVM_MAXIMUM_MEMORY="2048m"
